GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlyYSIsImlkIjoiNjM2ZTk5ZDVkMGZiZmMyMWQ0OGYyZDFhIiwiaWF0IjoxNjc3NDk2NzYxLCJleHAiOjE2Nzc1MDAzNjF9.RO9fTFBRhUJdckacaiDUAjNd2KjgKMhPsHmjrh_JEZk

###
GET  http://localhost:3003/api/blogs/636eaa4fc98d54a115f41ce3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlyYSIsImlkIjoiNjM2ZTk5ZDVkMGZiZmMyMWQ0OGYyZDFhIiwiaWF0IjoxNjY4NTA2MDA2LCJleHAiOjE2Njg1MDk2MDZ9.c7A4RapQoYYfdk8h0tQKLoJyUYXTyNoHR4LFxgE3ceM

###
GET  http://localhost:3003/api/blogs/1

###
DELETE  http://localhost:3003/api/blogs/636ea6de4e04bcd00fcc2a55
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlyYSIsImlkIjoiNjM2ZTk5ZDVkMGZiZmMyMWQ0OGYyZDFhIiwiaWF0IjoxNjY4NTA2MDA2LCJleHAiOjE2Njg1MDk2MDZ9.c7A4RapQoYYfdk8h0tQKLoJyUYXTyNoHR4LFxgE3ceM

###
DELETE  http://localhost:3003/api/blogs/1

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlyYSIsImlkIjoiNjM2ZTk5ZDVkMGZiZmMyMWQ0OGYyZDFhIiwiaWF0IjoxNjY4NTA2MDA2LCJleHAiOjE2Njg1MDk2MDZ9.c7A4RapQoYYfdk8h0tQKLoJyUYXTyNoHR4LFxgE3ceM

{
  "title": "Blog Test",
  "author": "Ira",
  "url": "/",
  "likes": 0
}

###
POST http://localhost:3003/api/blogs/6381fab8925381be43a95c38/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlyYSIsImlkIjoiNjM2ZTk5ZDVkMGZiZmMyMWQ0OGYyZDFhIiwiaWF0IjoxNjc3NTA2NDc0LCJleHAiOjE2Nzc1MTAwNzR9.Ijej0xtV_Emo4rE9xkfVR_lkXZUtOPiD0fbCo9kThMg

{
  "comment": "Blog Comment 4"
}

###
GET http://localhost:3003/api/blogs/6381fab8925381be43a95c38/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlyYSIsImlkIjoiNjM2ZTk5ZDVkMGZiZmMyMWQ0OGYyZDFhIiwiaWF0IjoxNjc3NTA2NDc0LCJleHAiOjE2Nzc1MTAwNzR9.Ijej0xtV_Emo4rE9xkfVR_lkXZUtOPiD0fbCo9kThMg

###
PATCH  http://localhost:3003/api/blogs/63628693a84f1535b6fd3a9a HTTP/1.1
content-type: application/json

{
  "likes": 3
}

###
PUT  http://localhost:3003/api/blogs/636eaa0bbd64c9788f7fb4ed HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlyYSIsImlkIjoiNjM2ZTk5ZDVkMGZiZmMyMWQ0OGYyZDFhIiwiaWF0IjoxNjY4NTA2MDA2LCJleHAiOjE2Njg1MDk2MDZ9.c7A4RapQoYYfdk8h0tQKLoJyUYXTyNoHR4LFxgE3ceM

{
  "likes": 6
}

###
PUT  http://localhost:3003/api/blogs/1 HTTP/1.1
content-type: application/json

{
  "likes": 5
}

### Users request

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
  "username": "ira",
  "name": "Ira User",
  "password": "iraPassword"
}


### Login request

###
POST http://localhost:3003/api/login/ HTTP/1.1
content-type: application/json

{
  "username": "root",
  "password": "password"
}

###
POST http://localhost:3003/api/login/ HTTP/1.1
content-type: application/json

{
  "username": "ira",
  "password": "iraPassword"
}
