GET http://localhost:3001/api/persons
###

GET http://localhost:3001/api/persons/6362904ec989e7d23f64aef3
###

DELETE  http://localhost:3001/api/persons/6362904ec989e7d23f64aef3

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Irina",
    "number": "040-22334455"
}

###
PUT http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Irina-updated",
    "number": "040-22334456"
}
