GET http://localhost:3003/api/blogs

###
GET  http://localhost:3003/api/blogs/63615445d98dd4ab8bca9a3e

###
GET  http://localhost:3003/api/blogs/1

###
DELETE  http://localhost:3003/api/blogs/63628693a84f1535b6fd3a9a

###
DELETE  http://localhost:3003/api/blogs/1

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNmFiZWE1MjUwNWQzOGQ0NGI3OGViOCIsImlhdCI6MTY2ODAwNjgwN30.H1Tmzg6oGp5urN8ZpZ41gHSjiDBL0V6avLFwqWzKFWU

{
  "title": "New blog",
  "author": "Ira",
  "url": "/",
  "likes": 0
}

###
PATCH  http://localhost:3003/api/blogs/63628693a84f1535b6fd3a9a HTTP/1.1
content-type: application/json

{
  "likes": 3
}

###
PUT  http://localhost:3003/api/blogs/63642fdaf0c4646a49fd0b6f HTTP/1.1
content-type: application/json

{
  "likes": 5
}

###
PUT  http://localhost:3003/api/blogs/1 HTTP/1.1
content-type: application/json

{
  "likes": 5
}

### Users request

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
  "username": "root",
  "name": "Ira",
  "password": "password"
}


### Login request

###
POST http://localhost:3003/api/login/ HTTP/1.1
content-type: application/json

{
  "username": "root",
  "password": "password"
}
